Styling NavBar
CraftAcademy/Glocal_news-Client pull request #16
Opened 2019-06-02 11:54 UTC by Carrosen

# [PT Story](https://www.pivotaltracker.com/story/show/166374521)

## Changes we propose in this PR
* Styling of NavBar with colours, see screenshot

## What we have learned
* Semantic UI react

![Screenshot from 2019-06-02 13-51-39](https://user-images.githubusercontent.com/48297491/58760850-bf454d00-853d-11e9-9f8d-78ca856304d6.png)

![Screenshot from 2019-06-02 13-53-28](https://user-images.githubusercontent.com/48297491/58760858-ddab4880-853d-11e9-8ddb-07026318ded9.png)

2019-06-02 14:22 UTC, raptorf1 requested changes
Other than my comment, fantastic job as always ;)

2019-06-02 14:22 UTC, raptorf1 commented on src/Components/HeaderCategory.jsx
> +const categories = [
Just a little comment. Categories are 13 without the `news`.

https://glocal-news.herokuapp.com/api/v1/categories

2019-06-03 11:45 UTC, oliverochman commented on src/Components/HeaderCategory.jsx
> +  {name: 'News', color: 'red'},
why are you not fetching the categories from the backend?

2019-06-03 13:40 UTC, faraznaeem approved these changes

2019-06-03 13:40 UTC, merged