Visitor can filter articles based on CATEGORIES
CraftAcademy/Glocal_news-Client pull request #20
Opened 2019-06-04 12:40 UTC by leiter007

# [PT Story](https://www.pivotaltracker.com/story/show/166152055)

## Changes proposed in this pull request:
* Integration test for filtering articles by category via header category tabs
* Added component for ArticlesByCategory which filters articles on category - either by clicking in the tabs or directly from the URL path
* Refactors paths in App.js to redirect to ArticlesByCategory component for all articles, including landing page   
* Removes ListOfArticles component since not needed anymore

## What I have learned working on this feature:
* Changing states based on ComponentDidUpdate
* Props, states and inheritance...

Screenshot:

2019-06-04 12:54 UTC, Carrosen reviewed
Awesome guys

2019-06-04 17:33 UTC, raptorf1 requested changes

2019-06-04 17:33 UTC, raptorf1 commented on src/index.js
> +axios.defaults.baseURL = 'http://localhost:3002'
back to heroku please :P

2019-06-05 06:36 UTC, leiter007 commented on src/index.js
> +axios.defaults.baseURL = 'http://localhost:3002'
Ah yes, done! :) Thank you

2019-06-05 07:09 UTC, oliverochman commented on src/Components/HeaderMain.jsx
> +state = {
indentation

2019-06-05 07:19 UTC, leiter007 commented on src/Components/HeaderMain.jsx
> +state = {
Done

2019-06-05 09:35 UTC, oliverochman requested changes

2019-06-05 09:35 UTC, oliverochman commented on src/Components/HeaderMain.jsx
> +// const countryOptions = [
why is this commented out?

2019-06-05 09:56 UTC, raptorf1 commented on src/Components/HeaderMain.jsx
> +// const countryOptions = [
done

2019-06-05 10:13 UTC, oliverochman approved these changes

2019-06-05 10:13 UTC, merged